# Generated by Django 5.2.5 on 2025-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding of the content', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='embedding_updated',
            field=models.DateTimeField(blank=True, help_text='When embeddings were last updated', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding of the excerpt', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding of the title', null=True),
        ),
    ]
