# Generated by Django 5.2.5 on 2025-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from default'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword to optimize this post for.', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description (160 chars max) for search engines.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Prevent search engines from following links in this post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Facebook/Open Graph description (300 chars max)', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Facebook/Open Graph image (1200x630px recommended)', null=True, upload_to='blog_images/og/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Facebook/Open Graph title (95 chars max)', max_length=95),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_score',
            field=models.IntegerField(default=0, help_text='SEO score out of 100 (calculated automatically)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to use post title.', max_length=60),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter card description (200 chars max)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (70 chars max)', max_length=70),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for category page (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title for category page (60 chars max)', max_length=60),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for tag page (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title for tag page (60 chars max)', max_length=60),
        ),
    ]
